---
- name: Check if amplify is installed
  stat:
    path: /etc/init.d/amplify-agent
  register: amplify_installed

- name: Install amplify
  block:
    - name: Download amplify installer
      get_url:
        url: https://github.com/nginxinc/nginx-amplify-agent/raw/master/packages/install.sh
        dest: /root/install.sh
        mode: '0500'
    - name: Install amplify
      shell: |
        API_KEY='{{ nginx_amplify_key }}' sh ./install.sh
    - name: Copy nginx config files
      copy:
        src: 'stub_status.conf'
        dest: '/etc/nginx/conf.d/stub_status.conf'
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx
  when: not amplify_installed.stat.exists
