---
- hosts: prometheus
  gather_facts: true

  pre_tasks:
    - debug:
        msg: "Target OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Gather OS specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - "os_vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "os_vars/{{ ansible_distribution }}.yml"
        - "os_vars/defaults.yml"
      tags: [all]

  roles:
    - role: common
    - role: cloudalchemy.prometheus
      vars:
        prometheus_web_external_url: /prometheus/
        prometheus_web_listen_address: "127.0.0.1:9090"
        prometheus_targets:
          node:
            - targets:
                - 127.0.0.1:9100  # node exporter
                - 127.0.0.1:3000  # grafana
                - 127.0.0.1:1880  # NodeRed
              labels:
                env: localhost
        prometheus_scrape_configs:
          - job_name: "prometheus"
            metrics_path: "{{ prometheus_metrics_path }}"
            static_configs:
              - targets:
                  - "127.0.0.1:9090"
          - job_name: "node"
            file_sd_configs:
              - files:
                  - "{{ prometheus_config_dir }}/file_sd/node.yml"
      tags: [grafana]
    - role: cloudalchemy.grafana
      vars:
        grafana_address: 127.0.0.1
        grafana_url: "http://{{ grafana_address }}:{{ grafana_port }}/grafana"
        serve_from_sub_path: true
        grafana_security:
          admin_user: admin
          admin_password: admin123
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost:9090/prometheus/'
            basicAuth: false
        grafana_dashboards:
          - dashboard_id: 3590
            revision_id: 1
            datasource: prometheus
      tags: [prometheus]
#    - role: node-exporter
#      vars:
#        node_exporter_version: 1.3.1
#        node_exporter_arch: amd64
    - role: cloudalchemy.node_exporter
      vars:
        - node_exporter_web_listen_address: "127.0.0.1:9100"
      tags: [node_exporter]
    - role: nodered
      vars:
        nodered_user_certificate: false
        nodered_nginx_vhost: false
        domain_name: '{{ ansible_host }}'
      tags: [nodered]
    - role: nginx-reverse-proxy
      tags: [nginx, nodered]