---
- hosts: prometheus
  gather_facts: true
  roles:
    - role: common
    - role: node-exporter
      vars:
        node_exporter_version: 1.3.1
        node_exporter_arch: amd64
    - role: cloudalchemy.prometheus
      vars:
        prometheus_targets:
          node:
            - targets:
              - 127.0.0.1:9100
              - 127.0.0.1:3000
              labels:
                env: demosite