---
- hosts: mosquitto
  gather_facts: true
  roles:
    - role: common
    - role: mosquitto
    - role: nodered
      tags: ['nodered']
    - role: grafana
      tags: ['grafana']
    - role: nginx
      tags: ['nginx']