---
- hosts: grafana
  gather_facts: true
  roles:
    - role: common
    - role: cloudalchemy.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin123
#    - role: grafana
