- name: Install nodejs 12 installer
  shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"
    # warn: false

# - name: Install NodeRed
#   shell: npm install -g --unsafe-perm node-red

- name: Install nodejs
  apt:
    name:
      - nodejs
    state: present
    update_cache: yes

# - name: Install forever package
#   npm:
#     name: forever
#     global: yes
#     state: present

- name: Node RED
  npm:
    name: node-red
    global: yes
    production: yes
    state: present

# - name: Run Node RED
#   shell: forever start /usr/local/bin/node-red

- name: Install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Enable node-red on pm2
  shell: |
    pm2 start /usr/bin/node-red -- -v
    pm2 save
    pm2 startup

- name: Install certbot
  apt:
    name: certbot
    state: present

- name: Generate certificates
  shell: certbot certonly --standalone -m {{ certbot_email }} -d {{ certbot_domain }} --agree-tos -n

- name: Copy nodered config files
  template:
    src: "settings.js.j2"
    dest: "/root/.node-red/settings.js"
    owner: root
    group: root
    mode: '0644'
  notify: Restart NodeRed

# - name: Generate password
#   shell: node -e "console.log(require('bcryptjs').hashSync(process.argv[1], 8));" your-password-here
#   args:
#     chdir: /usr/lib/node_modules/node-red

- name: Add NodeRed Vhost
  template:
    src: vhost.conf.j2
    dest: '/etc/nginx/sites-enabled/nodered.conf'
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx  