- name: Install required packages
  apt:
      name:
          - apt-transport-https
          - curl
          - git
          - gcc
          - g++
          - htop
          - make
      state: present
      update_cache: yes

